### ISSUE TITLE
Remove class "row" from NPS table div for proper alignment

### ISSUE THREAD

**Issue by maziminke** [tpartner/LimeSurvey-Net-Promoter-Score#1]
I wasn't able to center the main .nps-table DIV, only by removing class "row" at this row:
    `<div class="{{ coreClass }} nps-table" role="radiogroup" aria-labelledby="ls-question-text-{{ name }}">`

**Comment by tpartner** [comment]
Thanks for the feedback. That should have been taken care of in line 19 of _nps.css_ but I see no harm in removing the class.

- https://github.com/tpartner/LimeSurvey-Net-Promoter-Score/commit/a64523b37ba025a533ec71f19efd696af9fdcc54
