### ISSUE TITLE
NPS problem with arabic translation 

### ISSUE THREAD

**Issue by RIADH-KH** [tpartner/LimeSurvey-Net-Promoter-Score#10]
Hello Tony
I realised that the nps is breaking with the arabic question translation
When I press one of the buttum from 0 to 10 the green circle of list radio buttum moves to the left and the screen becomes very large.
I have renamed the Lsg file as a tex
Im using LS 6.4  and  I tried all the core themes of LS and it is the same problem
Sorry for my english  
Thanks
[limesurvey_group_97.lsg.txt](https://github.com/tpartner/LimeSurvey-Net-Promoter-Score/files/13509421/limesurvey_group_97.lsg.txt)

**Comment by tpartner** [comment]
I will need a .lss export to test.

**Comment by RIADH-KH** [comment]
I'm Sorry I Know that you leave in Canada I hope that it is not too early for you ( I'm from Tunisia)
I have renamed the Lss file as a tex
[limesurvey_survey.txt](https://github.com/tpartner/LimeSurvey-Net-Promoter-Score/files/13512169/limesurvey_survey.txt)
Thanks

**Comment by tpartner** [comment]
Fixed - https://github.com/tpartner/LimeSurvey-Net-Promoter-Score/commit/df30338b227e3c72f30e0a2c9b1aeb880638985f

**Comment by RIADH-KH** [comment]
Thanks a lot 
But do not forget to change " Last update - 2023-01-17 08:00" in the new css file to " Last update - 2023-11-30 08:00"
Thanks
