### ISSUE TITLE
Setting label "Show/Hide colours" is confusing

### ISSUE THREAD

**Issue by maziminke** [tpartner/LimeSurvey-Net-Promoter-Score#2]
We should simply ask "Show colours" since the options are "yes/no".

**Comment by tpartner** [comment]
Thanks for the feedback. 

Fixed - https://github.com/tpartner/LimeSurvey-Net-Promoter-Score/commit/d71a9c62622ead9c57a87a8fe2f468c0d3b36fb4 .
