### ISSUE TITLE
Setting "Show/Hide colours" can't be change if survey is active

### ISSUE THREAD

**Issue by maziminke** [tpartner/LimeSurvey-Net-Promoter-Score#3]
I am not sure why but for some reason the setting "Show/Hide colours" can't be changed if a survey is active. It works only after deactivating the survey.

**Comment by tpartner** [comment]
Fixed - https://github.com/tpartner/LimeSurvey-Net-Promoter-Score/commit/3fec6deceaac01839b3a5e90dbcea69e4100827c .
