### ISSUE TITLE
Options for adding scale left/right text are disabled for active surveys

### ISSUE THREAD

**Issue by maziminke** [tpartner/LimeSurvey-Net-Promoter-Score#4]
I am not sure why but for some reason the setting for adding scale left/right text can't be edited if a survey is active. It works only after deactivating the survey. See also the issue with the color setting.

**Comment by tpartner** [comment]
Fixed - https://github.com/tpartner/LimeSurvey-Net-Promoter-Score/commit/3fec6deceaac01839b3a5e90dbcea69e4100827c .
