### ISSUE TITLE
definition of colors

### ISSUE THREAD

**Issue by mbischof** [tpartner/LimeSurvey-Net-Promoter-Score#5]
color definitons should be possible in question settings, currently hard coded in css

**Comment by tpartner** [comment]
Fixed.

I added 10 settings instead of 3 so you can use a colour gradient.

- https://github.com/tpartner/LimeSurvey-Net-Promoter-Score/commit/418e680eead9441435649791ecf04172b64c8c48
- https://github.com/tpartner/LimeSurvey-Net-Promoter-Score/commit/8b7e18a066d26cd2140636dab3b937e4c01f49d0
