### ISSUE TITLE
Problem with left/right text

### ISSUE THREAD

**Issue by darimelo** [tpartner/LimeSurvey-Net-Promoter-Score#7]
In LimeSurvey 4.7 there are problems with left/right options. You cannot change "..." with other text
#3

**Comment by tpartner** [comment]
There is no version 4.7. It works for me in 4.4.11.

LS 4 is still quite buggy, did you try "Save and close"?

**Comment by darimelo** [comment]
![image](https://user-images.githubusercontent.com/42089729/109617768-17581b80-7b37-11eb-8f75-40bb920f35f3.png)
Yes, I tried "save and close" it

**Comment by tpartner** [comment]
I cannot reproduce the problem. Please update to the latest release and retest.

**Comment by lbray** [comment]
I'm getting the exact same problem.

**Comment by tpartner** [comment]
LS version?
