### ISSUE TITLE
Question theme settings not available at Version 5.0.5+210621

### ISSUE THREAD

**Issue by maziminke** [tpartner/LimeSurvey-Net-Promoter-Score#8]
I just manually uploaded the NPS question theme to a system using Version 5.0.5+210621. I am not able to find the theme settings e.g. for enabling the coloring. There is no "custom options" section.

**Comment by tpartner** [comment]
Maybe open a bug at LimeSurvey?

**Comment by maziminke** [comment]
Isn't this related to the neverending "Question themes at LS 4/5" issue you had been fighing for weeks? I think there already is a ticket for this, do you remember?

**Comment by maziminke** [comment]
Bug ticket: https://bugs.limesurvey.org/view.php?id=17408
